[settings]
    class = "CAppearanceTable"
    contained_by = "Monitor"
    doc_group = "01-Accounts"
    doc_descr = "an appearance table for an address"
    doc_route = "103-appearanceTable"
    produced_by = "chunks"
    go_output = "src/apps/chifra/pkg/types"
