[settings]
    class = "AppearanceCount"
    doc_group = "01-Accounts"
    doc_descr = "the number of records, file size, and last visited block for a given monitor"
    doc_route = "112-appearanceCount"
    attributes = "simponly"
    produced_by = "list, export"
