[settings]
    class = "ChunkPin"
    doc_group = "04-Admin"
    doc_descr = "a JSON object containing the results of pinning the Unchained Index"
    doc_route = "436-chunkPin"
    attributes = "simponly"
    produced_by = "chunks"
