[settings]
    class = "CChunkBloom"
    doc_group = "04-Admin"
    doc_descr = "internal-use only data model detailing a single bloom filter file"
    doc_route = "415-chunkBloom"
    produced_by = "chunks"
    go_output = "src/apps/chifra/pkg/types"
