[settings]
    class = "CChunkIndex"
    fields = "chunkindex.csv"
    doc_group = "04-Admin"
    doc_descr = "internal-use only data model detailing a single index chunk file"
    doc_route = "412-chunkIndex"
    doc_producer = "chunks"
    go_output = "src/apps/chifra/internal/chunks"
