[settings]
    class = "Function"
    contained_by = "abi, log, result, slurp, trace, transaction"
    doc_group = "05-Other"
    doc_descr = "a human-readable representation of a Solidity function call or event"
    doc_route = "506-function"
    produced_by = "abis, export"
    go_output = "src/apps/chifra/pkg/types"
    cache_type = "marshal_only"
