[settings]
    class = "CIpfsPin"
    doc_group = "04-Admin"
    doc_descr = "internal-use only data model detailing a single remote or local ipfs pinned file"
    doc_route = "421-ipfsPin"
    produced_by = "chunks"
    go_output = "src/apps/chifra/pkg/types"
