[settings]
    class = "MonitorClean"
    doc_group = "04-Admin"
    doc_descr = "report on cleaning dups out of monitors"
    doc_route = "427-monitorClean"
    produced_by = "monitors"
    go_output = "src/apps/chifra/internal/monitors"
