[settings]
    class = "CNamedBlock"
    fields = "namedblock.csv"
    doc_group = "02-Chain Data"
    doc_descr = "a block that has been given a particular name such as `first` or `latest`"
    doc_route = "214-namedBlock"
    doc_producer = "when"
    go_output = "src/apps/chifra/pkg/types"
