[settings]
    class = "Name"
    doc_group = "01-Accounts"
    doc_descr = "an association between a human-readable name and an address used throughout TrueBlocks"
    doc_route = "109-name"
    produced_by = "names"
    go_output = "src/apps/chifra/pkg/types"
