[settings]
    class = "CResult"
    fields = "result.csv"
    doc_group = "03-Chain State"
    doc_descr = "the result (articulated if possible, as bytes otherwise) of a call to a smart contract"
    doc_route = "309-result"
    doc_producer = "state"
    go_output = "src/apps/chifra/pkg/types"
    cache_type = "cacheable"
    cache_by = "address,block,fourbyte"
