[settings]
    class = "CStatus"
    fields = "status.csv"
    doc_group = "04-Admin"
    doc_descr = "status-related data about the TrueBlocks system including the server and local binary caches"
    doc_route = "403-status"
    doc_alias = "Status"
    doc_producer = "status"
    go_output = "src/apps/chifra/internal/status"
