[settings]
    class = "Transaction"
    contained_by = "block"
    doc_group = "02-Chain Data"
    doc_descr = "transaction data as returned from the RPC (with slight enhancements)"
    doc_route = "206-transaction"
    produced_by = "transactions, export"
    contains = "storageslot, trace, statement"
    cache_type = "cacheable"
    cache_by = "tx"
