[settings]
name = status

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
json = true

[formats]
trans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
txrans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{TRACEID}]\t[{FROM}]\t[{TO}]\t[{VALUE}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[{ISERROR}]\t[{ENCODING}]\t[{ARTICULATED}]

[[watches]]
list = [
    { address = "0x744d70fdbe2ba4cf95131626614a1763df805b9e", name = "StatusNetwork", firstBlock = 3898960, color = "green_c", enabled = true },
    { address = "0xa1c957c0210397d2d0296341627b74411756d476", name = "TokenFactory", firstBlock = 3898915, color = "green_c", enabled = true },
    { address = "0x52ae2b53c847327f95a5084a7c38c0adb12fd302", name = "Controller", firstBlock = 3899582, color = "green_c", enabled = true }
]

# make sure to always put arrays at the end of the file
