[settings]
    class = "CAppearance"
    fields = "appearance.csv"
    contained_by = "Monitor"
    doc_group = "01-Accounts"
    doc_descr = "an appearance (`<blockNumber,transactionIndex>`) of an address anywhere on the chain (note that in some cases, not all fields will appear depending on the command)"
    doc_route = "101-appearance"
    doc_producer = "list, export, blocks, chunks"
    go_output = "documentation only"
    cache_type = "marshal_only"
    disable_go = true