[settings]
class="CChunkPinReport"
fields="chunkpinreport.csv"
doc_group="04-Admin"
doc_descr="a JSON object containing the results of pinning the Unchained Index"
doc_route="412-chunkPinReport"
doc_producer="chunks"
go_output="src/apps/chifra/internal/chunks"
