[settings]
class="CIpfsPin"
fields="ipfspin.csv"
doc_group="04-Admin"
doc_descr="internal-use only data model detailing a single remote or local ipfs pinned file"
doc_route="406-ipfsPin"
doc_producer="chunks"
go_output="src/apps/chifra/internal/chunks/"
