[settings]
class="CReceipt"
fields="receipt.csv"
contained_by="Transaction"
doc_group="02-Chain Data"
doc_descr="receipt data as returned from the RPC (with slight enhancements)"
doc_route="205-receipt"
doc_producer="receipts, export"
go_output="src/apps/chifra/pkg/types"
cache_type="cacheable"
cache_by="block"
cache_as="group"
