[settings]
class="CTraceFilter"
fields="tracefilter.csv"
doc_group="02-Chain Data"
doc_descr="used by chifra traces --filter option to query for traces"
doc_route="212-traceFilter"
doc_producer="traces"
go_output="src/apps/chifra/pkg/types/"
