[display]
to_screen = true
use_color = true
show_logs = true
max_width = 180
check_balances = false

[formats]
screen_fmt1 = [{CONTRACT}]  [{BLOCKNUMBER}].[{TRANSACTIONINDEX}].[{DATE}]  [{FROM}]  [{ETHER}]  [{FUNCTION}]\n\tinput: [{INPUT}]\n\thash: [{HASH}]\n
screen_fmt2 = [{DATE}]\t[{FROM}]\t[{TO}]\t[{ETHER}]\t[{FUNCTION}]\t[{ISERROR}]\t[{BLOCKNUMBER}]\t[{HASH}]\n
screen_fmt = [{HEAD}]\n\
	\tdate: @[{DATE}]# timestamp: @[{TIMESTAMP}]#\n\
	\tfrom: @[{FROM}]# to: @[{TO}]# value: @[{w:30:VALUE}]# \n\
	\thash: @[{HASH}]# \n\
	\tblockNumber: @[{BLOCKNUMBER}]# txIndex: @[{TRANSACTIONINDEX}]#\n\
	\tinput: @[{INPUT}]#\n\
	[{P}]

[export]
to_export = false
export_header = timestamp\tdate\tfrom\tto\tvalue\tether\tfunction\tinput\tisError\tisInternalTx\tgas\tgasUsed\tblockNumber\thash\n
export_fmt = [{TIMESTAMP}]\t[{DATE}]\t[{FROM}]\t[{TO}]\t[{VALUE}]\t[{ETHER}]\t[{FUNCTION}]\t[{INPUT}]\t[{ISERROR}]\t[{ISINTERNALTX}]\t[{GAS}]\t[{GASUSED}]\t[{BLOCKNUMBER}]\t[{HASH}]\n
export_fmt2 = insert into transactions values ('[{HASH}]','[{FROM}]','[{FUNCTION}]',[{ETHER}]);\n

[watches]
nWatches = [{NWATCHES}]
[{WATCHES}]
[[watches2]]
[{JSON_WATCH}]
[master]
#firstBlock=<alternative_first_block>
