[settings]
name = CMT

[display]
accounting = false
logs = false
trace = false
single = false
parse = false
json = true

[fields]
hide=
show=
show_example_all = CTransaction:all|CReceipt:all|CLogEntry:all|CTrace:all|CTraceResult:all|CTraceAction:all|CParameter:all
show_example_logs = \
	CTransaction: none| \
	CReceipt: none, logs \
	CLogEntry: none, articulatedLog \
	CTrace: none
	
[formats]
trans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
txrans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{TRACEID}]\t[{FROM}]\t[{TO}]\t[{ETHER}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[TRUE{b:ISERROR}]\t[{ENCODING}]\t[{ARTICULATED}]

[[watches]]
list = [
    { address = "0xf85feea2fdd81d51177f6b8f35f0e6734ce45f5f", name = "CMT", firstBlock = 4654938, lastBlock = 6250000 },
]
