[settings]
name = Giveth
index = 50176

[display]
#accounting = true
#debug = true
#logs = true
#trace = true
#single = true
#autocorrect = true
#parse = true

[formats]
trans_fmt = [{DATE} ] \
            [{BLOCKNUMBER} ][{TRANSACTIONINDEX} ] \
            [{FROM} ][{TO} ][{ETHER} ][{ISERROR} ] \
            [\r\n\tarticulated:\t{ARTICULATED}] \
            [\r\n\tgas cost:\t{GASCOST}][ (used/price: {GASUSED}][ @ {GASPRICE})] \
            [\r\n\tevents:\t\t{EVENTS}]

[[watches]]
list = [
    { address = "0x5ADF43DD006c6C36506e2b2DFA352E60002d22Dc", name = "FundForwarder", firstBlock = 4448139, color = "green_c" },
    { address = "0x8702b8D7a1EeFEc7E54636E26A9323Dc96A8Dc25", name = "Beneficiary", firstBlock = 3523076, color = "teal_c" },
    { address = "0x839395e20bbB182fa440d08F850E6c7A8f6F0780", name = "EscapeHatchCaller", firstBlock = 1908822, color = "magenta_c" },
    { address = "0x8f951903c9360345b4e1b536c7f5ae8f88a64e79", name = "EscapeHatchDestination", firstBlock = 3235281, color = "blue_c" }
]

# make sure to always put arrays at the end of the file
