[settings]
name = gonetwork

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
json = true

[fields]
hide=
show=

[formats]
trans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
xtrans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{TRACEID}]\t[{FROM}]\t[{TO}]\t[{VALUE}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[{ISERROR}]\t[{ENCODING}]\t[{ARTICULATED}]

[[watches]]
list = [
    { address = "0x423b5f62b328d0d6d44870f4eee316befa0b2df5", name = "GoNetwork", firstBlock = 5449023, color = "green_c" }
]


# make sure to always put arrays at the end of the file
