[version]
    current = "v0.40.0-beta"

[settings]
    cachePath = ""
    defaultChain = "mainnet"
    defaultGateway = "https://ipfs.unchainedindex.io/ipfs"
    indexPath = ""

[keys]
    [keys.etherscan]
        apiKey = ""
    [keys.infura]
        apiKey = ""
        secret = ""
    [keys.pinata]
        apiKey = ""
        jwt = ""
        secret = ""
    [keys.trueblocks]
        license = ""
        apiKey = ""

[chains]
    [chains.gnosis]
        chainId = "100"
        localExplorer = "http://localhost:1234"
        remoteExplorer = "https://gnosisscan.io/"
        rpcProvider = "https://gnosischain-rpc.gateway.pokt.network"
        symbol = "XDAI"
    [chains.mainnet]
        chainId = "1"
        localExplorer = "http://localhost:1234"
        remoteExplorer = "https://etherscan.io"
        rpcProvider = "http://localhost:8545"
        symbol = "ETH"
    [chains.optimism]
        chainId = "10"
        localExplorer = "http://localhost:1234"
        remoteExplorer = "https://optimistic.etherscan.io"
        rpcProvider = "https://mainnet.optimism.io"
        symbol = "OPT"
    [chains.polygon]
        chainId = "80001"
        localExplorer = "http://localhost:1234"
        remoteExplorer = "https://mumbai.polygonscan.com"
        rpcProvider = "https://rpc-mumbai.maticvigil.com"
        symbol = "MATIC"
    [chains.sepolia]
        chainId = "11155111"
        localExplorer = "http://localhost:1234"
        remoteExplorer = "https://sepolia.otterscan.io/"
        rpcProvider = "http://localhost:8548"
        symbol = "ETH"
