name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TrueBlocks repo
        uses: actions/checkout@v2
      - name: Install prerequistes
        run: |
          sudo apt-get install build-essential git cmake python python-dev libcurl3-dev clang-format jq
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github_action
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Build TrueBlocks
        run: |
          mkdir build && cd build
          cmake ../src
          make -j 4
      - name: Run SSH tunnel
        run: |
          ssh -i ~/.ssh/github_action -o StrictHostKeyChecking=no -N -v ${{secrets.SSH_COMMAND}} -p 36963 -L 36963:localhost:8545 </dev/null &
          sleep 5
          find /home/runner/.local/share/trueblocks/
          cat /home/runner/.local/share/trueblocks/trueBlocks.toml
          export PATH=$PATH:/home/runner/work/trueblocks-core/trueblocks-core/bin:/home/runner/work/trueblocks-core/trueblocks-core/bin/tests
          which chifra
          which cacheStatus
          which getBlocks
          curl --data '{"method":"eth_getBlockByNumber","params":["latest", true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:36963 | jq
      - name: Finish
        run: |
          echo "ðŸ This job's status is ${{ job.status }}"
