name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Prerequistes
        run: |
          sudo apt install build-essential git cmake python python-dev libcurl3-dev clang-format jq
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github_action
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Build TrueBlocks
        run: |
          mkdir build && cd build
          cmake ../src
      - name: Run SSH Process and Tests
        run: |
          nohup ssh -i ~/.ssh/github_action -o StrictHostKeyChecking=no -N -v ${{secrets.SSH_COMMAND}} -p 36963 -L 36963:localhost:8545 > foo.out 2> foo.err < /dev/null &
          cat foo.err
          #mkdir -p build && cd build
          #cmake ../src
          #make test-all
          curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"fromBlock": 2000000, "toBlock": 11000000, "topics": [["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"], ["0x0000000000000000000000008bfbb529a9e85fdc4b70a4fcdc0d68bb298b8816"]]}],"id":3}' http://localhost:36963curl --data '{"method":"eth_getBlockByNumber","params":["0x3", true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545 | jq
          chifra blocks 12
      - run: echo "ðŸ This job's status is ${{ job.status }}"
