name: GitHub Actions Demo
on: [pull_request, push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TrueBlocks repo
        uses: actions/checkout@v2
      - name: Install prerequistes
        run: |
          sudo apt-get install build-essential git cmake python python-dev libcurl3-dev clang-format jq tree
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github_action
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Build TrueBlocks
        run: |
          mkdir -p build && cd build
          cmake ../src
          make -j 4
      - name: Run SSH tunnel and tests
        run: |
          ssh -i ~/.ssh/github_action -o StrictHostKeyChecking=no -N -v ${{secrets.SSH_COMMAND}} -L 36963:localhost:36963 >/dev/null 2>err.log </dev/null &
          sleep 3
          echo "Checking tunnel... (if the exit code is other than 0, then the tunnel is down)"
          curl -s -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://localhost:36963 > /dev/null
          echo "Tunnel OK"
          mkdir -p /home/runner/.local/share/trueblocks
          touch /home/runner/.local/share/trueblocks/trueBlocks.toml
          sed -i 's/8545/36963/' /home/runner/.local/share/trueblocks/trueBlocks.toml
          sed -i 's/etherscan_key/junk/' /home/runner/.local/share/trueblocks/trueBlocks.toml
          echo etherscan_key = ${{secrets.ES_KEY}} >>/home/runner/.local/share/trueblocks/trueBlocks.toml
          export TOP=`pwd`
          export PATH=$PATH:$TOP/bin:$TOP/bin/test/
          # cat /home/runner/.local/share/trueblocks/trueBlocks.toml | mail jrush@quickblocks.io
          cat /home/runner/.local/share/trueblocks/trueBlocks.toml
          cd ./build
          chifra serve >/dev/null 2>&1 &
          make test-all
      - name: Finish
        run: |
          echo "ğŸ This job's status is ${{ job.status }}"
